language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
addons:
  postgresql: "9.3"
script: nosetests --with-coverage classic/tests/unit_tests
sudo: false
after_success:
 - coveralls
